UpdateReadme.md
pytorch/vision pull request #2732
Opened 2020-09-30 13:41 UTC by gujralsanyam22

UpdateReadme.md

2020-09-30 14:19 UTC, fmassa requested changes
Thanks for the PR!

I've left a few comments, and I believe there is one issue with formatting. Would you be willing to try to fix it?

2020-09-30 14:19 UTC, fmassa commented on README.rst
> +**Image Backend**
From rendering it on markdown, there doesn't seem to be any difference by making the titles bold, as it's already done by default. Can you revert those changes?

2020-09-30 14:19 UTC, fmassa commented on README.rst
> +6.) _libjpeg-turbo: https://libjpeg-turbo.org/
This doesn't seem to render correctly, can you revert this change? 
![image](https://user-images.githubusercontent.com/9110200/94696810-c1890880-0337-11eb-9d84-e6228efa2371.png)

2020-09-30 14:19 UTC, fmassa commented on README.rst
> +This is a utility library that downloads and prepares the  public datasets. We do not host or redistribute these datasets, vouch for their quality or fairness, or claim that you have license to use t
I think the `the` is unnecessary.

The `redistribute` I'm not sure, a Google search s[eemed to look as if `distribute` could be ok](https://wikidiff.com/distribution/redistribution).

2020-09-30 14:19 UTC, fmassa commented on README.rst
> +**Torchvision**
We haven't been consistent with the capitalization of torchvision in the past. We've written it both as torchvision as well as TorchVision. From this perspective, I would maybe leave this as is, but I'm bringing this to discussion with @dongreenberg

2020-10-01 09:47 UTC, t-vi commented
Context: https://blog.domenic.me/hacktoberfest/
Same similar thing in https://github.com/pytorch/text/pull/1018

2020-10-01 10:13 UTC, closed without merging