Added annotation typing to classification models
pytorch/vision pull request #2854
Opened 2020-10-21 13:53 UTC by frgfm

Hello folks :wave: 

As per #2025, annotation typing are welcome in torchvision. So I started with the classification modules of  `torchvision.models` in this PR. A few points of attention:
- I picked `Callable[..., nn.Module]` for module constructors (passing `BatchNorm2d` for instance), I'm unsure whether that is good choice? any recommendation?
-  I only used black styling in class constructors for now, the rest are only annotation typing additions.

Any feedback is welcome!

2020-10-21 15:20 UTC, pmeier requested changes
Hey @frgfm, thanks a lot for the PR! Could you please split this PR into multiple as it is very hard to review with that many changes. I think it would be best to do a separate PR for every model / file. 

I've reviewed the first three files and found a couple of things.

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/_utils.py
> +from torch import Tensor
Given that we don't need to use this in so many places and we already importing `torch`, couldn't we simply use `torch.Tensor`?

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/_utils.py
> +    def forward(self, x: Tensor) -> Tensor:
Shouldn't that be `-> Dict[str, torch.Tensor]`?

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/alexnet.py
> +from torch import Tensor
Same as above.

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/alexnet.py
> +def alexnet(pretrained: bool = False, progress: bool = True, **kwargs) -> AlexNet:
```suggestion
def alexnet(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> AlexNet:
```

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +    def any_requires_grad(self, input: List[Tensor]) -> Tensor:
```suggestion
    def any_requires_grad(self, input: List[Tensor]) -> bool:
```

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +    def forward(self, input: Union[Tensor, List[Tensor]]) -> Tensor:  # noqa: F811
`torch.script` is not able to handle `Union`. We need to annotate it as `torch.Tensor` for now and add an ignore for `mypy`.

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +              pretrained: bool, progress: bool, **kwargs) -> DenseNet:
```suggestion
              pretrained: bool, progress: bool, **kwargs: Any) -> DenseNet:
```

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +def densenet121(pretrained: bool = False, progress: bool = True, **kwargs) -> DenseNet:
```suggestion
def densenet121(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> DenseNet:
```

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +def densenet161(pretrained: bool = False, progress: bool = True, **kwargs) -> DenseNet:
```suggestion
def densenet161(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> DenseNet:
```

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +def densenet169(pretrained: bool = False, progress: bool = True, **kwargs) -> DenseNet:
```suggestion
def densenet169(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> DenseNet:
```

2020-10-21 15:20 UTC, pmeier commented on torchvision/models/densenet.py
> +def densenet201(pretrained: bool = False, progress: bool = True, **kwargs) -> DenseNet:
```suggestion
def densenet201(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> DenseNet:
```

2020-10-21 15:56 UTC, frgfm commented
@pmeier sure, I updated this PR to focus on `models._utils`. You got a dozen PRs incoming then haha

2020-10-21 16:05 UTC, pmeier commented
That is alright. I'll go through them one by one.

2020-10-21 16:10 UTC, pmeier requested changes
`mypy` CI [is failing](https://app.circleci.com/pipelines/github/pytorch/vision/4535/workflows/507b55a2-b19a-42b6-94c2-597db452e110/jobs/272328) with
```
torchvision/models/_utils.py:60: error:
Signature of "forward" incompatible with supertype "ModuleDict" [override]
        def forward(self, x: torch.Tensor) ->...
```

2020-10-21 17:18 UTC, pmeier commented
@frgfm Removing the annotation is not the way to go here. Either fix it or if it is unfixable (which might be the case here) use the correct annotations and add a `#type: ignore[override]` to the line.

2020-10-22 05:34 UTC, pmeier commented
The test failures are related. I'll look into it and get back to you.

2020-10-22 05:52 UTC, pmeier commented
@frgfm It seems torchscript is the offender here. I suspect it can't handle the `type: ignore` comment. Could you remove that to see if my suspicion is right?

If it is I'm not sure to move forward. We can't make torchscript *and* `mypy` happy.

2020-10-22 08:07 UTC, frgfm commented
@pmeier Yes, I figured out the same thing yesterday unfortunately.
When I remove the ignore, mypy throws the following:
```
error: Signature of "forward" incompatible
with supertype "ModuleDict"  [override]
```

Let me know which way you prefer to proceed with!

2020-10-22 08:12 UTC, pmeier commented
In general torchscript > mypy holds. Thus, while the type hints are nice to have, passing tests for torchscript is a requirement. Could you simply remove the `type: ignore` comment and push that change? It is not important for now if `mypy` fails, but the unit tests need to pass.

2020-10-22 08:21 UTC, fmassa commented
Yes.

The situation with torchscript is delicate, and if we need to chose between mypy and torchscript, torchscript wins.

In general, all torchvision models already have type annotation in the forward because they all support torchscript. The difference with mypy is that torchscript assumes that
- if no input type is passed to an argument, it's assumed to be a tensor
- return types are inferred

So if you want to play safe, I would say to only add type annotations to the constructor of the models, or the model builder functions. This way it won't affect torchscript, but mypy won't probably be happy either.

Which means that it might be hard to enable full mypy testing to the models.

2020-10-22 08:25 UTC, pmeier commented
> This way it won't affect torchscript, but mypy won't probably be happy either.

Right now, we allow untyped definitions. Thus, if we simply remove the annotations from `forward`, `mypy` should be happy.

2020-10-22 09:06 UTC, pmeier approved these changes
LGTM. Thanks a lot @frgfm. Note that the further process will be delayed, since we are currently preparing the next release of `torchvision`.

2020-10-22 10:02 UTC, frgfm commented
> LGTM. Thanks a lot @frgfm. Note that the further process will be delayed, since we are currently preparing the next release of `torchvision`.

Should I update 
```
from torch.jit.annotations import Dict
```
to 
```
from typing import Dict
```
though?

2020-10-22 10:05 UTC, pmeier commented
Yes that would be nice!

2020-10-22 11:44 UTC, fmassa approved these changes
Thanks!

2020-10-22 11:45 UTC, merged