[ONNX] Fix roi_align ONNX export
pytorch/vision pull request #3355
Opened 2021-02-05 18:31 UTC by KsenijaS

Allow export of roi_align when sampling rate is negative

2021-03-02 09:33 UTC, fmassa commented
@KsenijaS is the PR ready for review?

2021-03-04 23:58 UTC, KsenijaS commented
> @KsenijaS is the PR ready for review?

@fmassa  Yes, PR is ready for a review. It would be also good that some one from my team review it as well.
@neginraoof @BowenBao

2021-03-08 17:04 UTC, fmassa requested changes
The changes look generally good to me, but there is a syntax error in the warning message that needs to be fixed before merging

2021-03-08 17:04 UTC, fmassa commented on torchvision/ops/_register_onnx_ops.py
> +            warnings.warn("ONNX doesn't support negative sampling ratio, therefore is is set to 0 in order to be exported.)
This is a syntax error, as the `"` is missing in the end

2021-03-12 12:28 UTC, datumbox approved these changes
LGTM, thanks!

2021-03-12 12:43 UTC, merged