Update functional.py
pytorch/vision pull request #3918
Opened 2021-05-25 21:40 UTC by Gaurav7888

Replace torch.lstsq with torch.linalg.lstsq in perspective transform .

It would be good to fix this before the next release, so that users don't get those warnings.

2021-05-25 21:52 UTC, datumbox approved these changes
@Gaurav7888 welcome to PyTorch community! LGTM.

To merge this you will need to complete the CLA signing (you only need to do it once). Once the tests pass we can merge to master.

2021-05-25 22:03 UTC, datumbox commented on torchvision/transforms/functional.py
>      output: List[float] = res.squeeze(1).tolist()
You also need to update the following:
```suggestion
    output: List[float] = res.tolist()
```

2021-05-26 14:41 UTC, datumbox requested changes
@Gaurav7888 It seems that the two methods do not provide exactly the same results and this means that some of the tests break. See the CI.

To move forwards with this PR we will need to first fix the broken tests. Could you please let me know if you are interested in continuing the work of this PR?

2021-05-26 15:25 UTC, Gaurav7888 commented
@datumbox  Sure I would like to work upon this PR .

2021-05-26 15:35 UTC, datumbox commented
Awesome, we can fix the tests by updating their expected values. It should be an easy fix. :)

2021-05-26 15:38 UTC, Gaurav7888 commented
@datumbox  I found something useful regarding this issue
Why is the output of torch.lstsq drastically different than np.linalg.lstsq?

torch.lstq(a, b) solves minX L2∥bX−a∥ while np.linalg.lstsq(a, b) solves minX L2∥aX−b∥

a = torch.tensor([[1., 1, 1],
                  [2, 3, 4],
                  [3, 5, 2],
                  [4, 2, 5],
                  [5, 4, 3]])

b = torch.tensor([[-10., -3],
                  [ 12, 14],
                  [ 14, 12],
                  [ 16, 16],
                  [ 18, 16]])

a1 = a.clone().numpy()
b1 = b.clone().numpy()

x, _ = torch.lstsq(a, b)

x1, res, r1, s = np.linalg.lstsq(b1, a1)

print(f'torch_x: {x[:b.shape[1]]}')

print(f'np_x: {x1}')
Results:

torch_x: tensor([[-0.1145, -0.1047, -0.2863],
        [ 0.3591,  0.3372,  0.5407]])
np_x: [[-0.11452514 -0.10474861 -0.28631285]
 [ 0.35913807  0.33719075  0.54070234]]

2021-06-18 10:17 UTC, NicolasHug commented
Hi @Gaurav7888 , thanks for your work so far!

The current test failures are due to some instability in `torch.linalg.lstsq`, which actually returns different output across various executions:

```py
import torch
torch.set_printoptions(precision=10)

a = torch.tensor([[    3,     2,     1,     0,     0,     0,     0,     0],
                  [    0,     0,     0,     3,     2,     1,     0,     0],
                  [   32,     3,     1,     0,     0,     0, -1056,   -99],
                  [    0,     0,     0,    32,     3,     1,     0,     0],
                  [   30,    24,     1,     0,     0,     0,  -990,  -792],
                  [    0,     0,     0,    30,    24,     1,  -750,  -600],
                  [    2,    25,     1,     0,     0,     0,     0,     0],
                  [    0,     0,     0,     2,    25,     1,   -50,  -625]]).to(torch.float)
b = torch.tensor([ 0.,  0., 33.,  0., 33., 25.,  0., 25.])
torch.linalg.lstsq(a, b).solution
```

will sometimes output

```
tensor([ 1.0224266052e+00,  4.4453188777e-02, -3.1561851501e+00,
        -3.5440485924e-02,  1.0277750492e+00, -1.9492297173e+00,
        -2.9531884938e-03, -1.8849190092e-03])
```

and sometimes

```
tensor([ 1.0224264860e+00,  4.4453065842e-02, -3.1561782360e+00,
        -3.5440552980e-02,  1.0277750492e+00, -1.9492284060e+00,
        -2.9531936161e-03, -1.8849160988e-03])
```

ultimately leading to a big difference in pixel values.


It's a bit surprising since the matrix is well-conditioned:

```py
torch.linalg.cond(a, p=-2), torch.linalg.cond(a, p=2)
(tensor(0.0003948331), tensor(2532.7155761719))
```

but oh well.

I believe that changing the solver will help here. 'gels' seems to solve the instability and it is the only available driver for CPU and GPU, so let's use it:

```py
torch.linalg.lstsq(a, b, driver='gels').solution
```

I just pushed a fix, hopefully this will make the CI go green!

2021-06-18 10:43 UTC, NicolasHug approved these changes
unittest CI is green so let's merge!

This LGTM and @datumbox had approved this previously, modulo the failing tests which are now resolved.

Thanks @Gaurav7888 !

2021-06-18 10:44 UTC, merged