[Testing] Install cuda
pytorch/vision pull request #4145
Opened 2021-07-01 10:08 UTC by mszhanyi

2021-07-01 15:34 UTC, mszhanyi commented
@NicolasHug it looks recent pytorch change trigger a regression error.
https://app.circleci.com/pipelines/github/pytorch/vision/9376/workflows/2b47b22b-53f3-4d1f-be8e-5693b0861a74/jobs/689087

I install the release pytorch version, the build can pass.
https://github.com/mszhanyi/vision/blob/5a298742f9b03b658be211c47425d9262aae58d3/packaging/build_cmake.sh#L31-L32

2021-07-01 15:35 UTC, NicolasHug commented
@mszhanyi Indeed, this was reported in https://github.com/pytorch/pytorch/issues/61036 and hopefully should be fixed soon!

2021-09-10 14:16 UTC, malfet commented
This PR seems to break number of existing build configs, for example [cmake_linux_gpu](https://app.circleci.com/pipelines/github/pytorch/vision/10274/workflows/26212e6f-f41c-4179-a923-fe1d279defec/jobs/777300) now fails, because CUDA could not be find in "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" folder

2021-09-10 14:19 UTC, malfet requested changes
Please fix build failures and then request re-review.
Also, I would strongly recommend to separate updating CUDA versions and enabling the builds into a separate PRs.
For example, PR enabling Windows CUDA testing should not change packaging scripts, as as packaging TorchVision with CUDA currently works correctly, isn't it?

2021-09-10 14:19 UTC, malfet commented on packaging/build_cmake.sh
> +
This would be executed from both Windows and Linux build environment, which seems wrong

2021-09-26 06:54 UTC, closed without merging