Added missing typing annotations in datasets/hmdb51
pytorch/vision pull request #4169
Opened 2021-07-12 22:44 UTC by frgfm

Following up on #2025, this PR adds missing typing annotations in datasets/hmdb51.py.

Any feedback is welcome!

2021-07-15 12:30 UTC, pmeier requested changes
Thanks for the PR @frgfm! Unfortunately, the `mypy` failures are relevant:

```
torchvision/datasets/hmdb51.py:127: error: Incompatible types in assignment
(expression has type "Set[str]", variable has type "List[str]")  [assignment]
            selected_files = set(selected_files)
                             ^
Found 1 error in 1 file (checked 110 source files)
```

2021-07-20 05:15 UTC, pmeier reviewed
One more thing inline. Otherwise LGTM, thanks @frgfm. Test failures seem unrelated.

2021-07-20 05:15 UTC, pmeier commented on torchvision/datasets/hmdb51.py
> +        _selected_files = []
Instead of appending to a `list` and later turn it into a `set` why not start out with one?
```suggestion
        selected_files = set()
```

2021-07-20 05:15 UTC, pmeier commented on torchvision/datasets/hmdb51.py
> +        selected_files = set(_selected_files)
Follow-up to the comment above:
```suggestion
                    selected_files.add(video_filename)
```

2021-07-20 15:41 UTC, pmeier approved these changes
LGTM, thanks @frgfm!

2021-07-29 13:58 UTC, datumbox approved these changes
LGTM, I will merge after CI passes.

2021-07-29 14:49 UTC, datumbox commented
The failing tests are unrelated, merging.

2021-07-29 14:49 UTC, merged