Added warnings to mobile vision with links to ExecuTorch docs
pytorch/vision pull request #8616
Opened 2024-08-29 22:09 UTC by tstatler

Addresses [T200046828](https://www.internalfb.com/intern/tasks/?t=200046828). Adds warnings to mobile vision docs and links to ExecuTorch.

2024-08-29 22:19 UTC, svekars commented on docs/source/models/mobilenetv2.rst
> +    PyTorch Mobile is no longer actively supported. Please check out `ExecuTorch <https://pytorch.org/executorch-overview>`_, PyTorch’s all-new on-device inference library. You can also review our `e
```suggestion
    PyTorch Mobile is no longer actively supported. Please check out `ExecuTorch <https://pytorch.org/executorch-overview>`_, PyTorch’s all-new on-device inference library. You can also review our `end-to-end workflows <https://github.com/pytorch/executorch/tree/main/examples/portable#readme>`_ and the `source code <https://github.com/pytorch/executorch/tree/main/examples/models/mobilenet_v2>`__ for MobileNetV2.
```

2024-08-29 22:19 UTC, svekars commented on docs/source/models/mobilenetv3.rst
> +    PyTorch Mobile is no longer actively supported. Please check out `ExecuTorch <https://pytorch.org/executorch-overview>`_, PyTorch's all-new on-device inference library. You can also review our `e
```suggestion
    PyTorch Mobile is no longer actively supported. Please check out `ExecuTorch <https://pytorch.org/executorch-overview>`_, PyTorch's all-new on-device inference library. You can also review our `end-to-end workflows <https://github.com/pytorch/executorch/tree/main/examples/portable#readme>`_ and the `source code <https://github.com/pytorch/executorch/tree/main/examples/portable#readme>`__ for MobileNetV3.
```

2024-08-30 08:25 UTC, NicolasHug requested changes
Hi @tstatler , I don't think these models are related to executorch in any way. Perhaps there's a confusion between mobilevision (an internal project, I believe) and torchvision?

2024-08-30 15:24 UTC, svekars commented
> Hi @tstatler , I don't think these models are related to executorch in any way. Perhaps there's a confusion between mobilevision (an internal project, I believe) and torchvision?

@ali-khosh ^^

2024-08-30 16:15 UTC, closed without merging

2024-08-30 16:28 UTC, ali-khosh commented
I think these were false positives. Thanks for flagging Nicolas! Svetlana and I connected and we'll skip these changes.